name: Bump Casks

on:
  schedule:
    # Time is UTC, so below is running everyday at 4AM and 4PM PST
    - cron: "0 2,14 * * *"
  push:
    paths:
      - ".github/workflows/bump-casks.yml"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-casks:
    name: Bump Homebrew Cask
    runs-on: macos-latest
    outputs:
      pr: ${{ steps.bump.outputs.pr }}
    steps:
      - name: Homebrew Bump Cask (LanikSJ)
        id: bump
        uses: LanikSJ/homebrew-bump-cask@v3 # v3
        with:
          # Authentication token to use for pushing changes; use the built-in GITHUB_TOKEN or define a HOMEBREW_TOKEN secret
          token: ${{ secrets.HOMEBREW_TOKEN }}
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          # Bump all outdated casks in this tap
          tap: leeronr/homebrew-dedeprecated
          # Bump only these casks if outdated
          # cask: chromedriver, vlc@nightly, xld
          no_fork: true
          livecheck: true
          dryrun: false

  auto-merge:
    name: Auto Merge PRs
    runs-on: ubuntu-latest
    needs: bump-casks
    if: ${{ needs.bump-casks.outputs.pr != '' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge Pull Request
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          PR_NUMBER: ${{ needs.bump-casks.outputs.pr }}
        run: |
          gh pr merge $PR_NUMBER --auto --squash --delete-branch